spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: congestion-service
          uri: http://localhost:8081
          predicates:
            - Path=/control/congestion/**
          filters:
            - RewritePath=/control/congestion/(?<segment>.*), /${segment}

        - id: external-service
          uri: http://localhost:8081
          predicates:
            - Path=/control/external/**
          filters:
            - RewritePath=/control/external/(?<segment>.*), /${segment}

        - id: place-service
          uri: http://localhost:8082
          predicates:
            - Path=/place/**
          filters:
            - RewritePath=/place/(?<segment>.*), /${segment}

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user/**
            - Path=/auth/**
          filters:
            - RewritePath=/user/(?<segment>.*), /${segment}
            - RewritePath=/auth/(?<segment>.*), /${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://192.168.0.186:5173"
              - "http://58.127.241.84:5173"
              - "http://api.seoultravel.life"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
